
name: Shell commands

on: [push,]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: "Hello  World"
      - name: multiple commands
        run: |
          node -v
          npm -v
  